# Generated by Django 5.1.7 on 2025-05-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(default=0, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
