# Generated by Django 5.1.7 on 2025-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_starting', models.DateTimeField(verbose_name='Дата начала акции')),
                ('date_ending', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('image', models.ImageField(upload_to='specials/', verbose_name='Изображение')),
            ],
        ),
    ]
