# Generated by Django 5.1.7 on 2025-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_emailcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='email_images/'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
